### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by wzm2256** [ethanfetaya/NRI#6]
Line 93 os.mkdir   ----> os.makedirs
Line 46 default='logs'  ----> default='./logs'

**Comment by nzarnaghi** [comment]
I did these modifications, but it still does not work and gives me this error:

Namespace(batch_size=128, cuda=False, decoder='mlp', decoder_dropout=0.0, decoder_hidden=256, dims=4, dynamic_graph=False, edge_types=2, encoder='mlp', encoder_dropout=0.0, encoder_hidden=256, epochs=500, factor=True, gamma=0.5, hard=False, load_folder='', lr=0.0005, lr_decay=200, no_cuda=False, no_factor=False, num_atoms=5, prediction_steps=10, prior=False, save_folder='./logs', seed=42, skip_first=False, suffix='_springs5', temp=0.5, timesteps=49, var=5e-05)
Traceback (most recent call last):
  File "train.py", line 93, in <module>
    os.makedirs(save_folder)
  File "C:\Users\nzarnaghi\AppData\Local\Continuum\anaconda3\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: './logs/exp2020-07-08T12:45:08.925712/'

**Comment by lylyjy** [comment]
Did you solve it?
I have the same error.

**Comment by grgn96** [comment]
I am a Windows user and solved it without modifying line 46 as @wzm2256.
I changed line 93 with the following
```
save_folder = pathvalidate.sanitize_filepath(save_folder,"_","auto")
    if pathvalidate.is_valid_filepath(save_folder):   
        try: os.makedirs(save_folder)        
        except WindowsError():
            print("Check directory creation!\n")
```

the [pathvalidate](https://pathvalidate.readthedocs.io/en/latest/index.html) library is required.

**Comment by safermi** [comment]
I did these modifications, but it still does not work and gives me this error:C:\Users\sl\Desktop\NRI-master>python train.py
Namespace(no_cuda=False, seed=42, epochs=500, batch_size=128, lr=0.0005, encoder_hidden=256, decoder_hidden=256, temp=0.5, num_atoms=5, encoder='mlp', decoder='mlp', no_factor=False, suffix='_springs5', encoder_dropout=0.0, decoder_dropout=0.0, save_folder='logs', load_folder='', edge_types=2, dims=4, timesteps=49, prediction_steps=10, lr_decay=200, gamma=0.5, skip_first=False, var=5e-05, hard=False, prior=False, dynamic_graph=False, cuda=False, factor=True)
Traceback (most recent call last):
  File "C:\Users\sl\Desktop\NRI-master\train.py", line 93, in <module>
    os.makedirs(save_folder)
  File "<frozen os>", line 225, in makedirs
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'logs/exp2023-10-10T16:59:42.303545/'这是什么意思
Can you tell me how to modify it，Thank you

> 我是 Windows 用户，并在没有将第 46 行修改为 .我用以下内容更改了第 93 行
> 
> ```
> save_folder = pathvalidate.sanitize_filepath(save_folder,"_","auto")
>     if pathvalidate.is_valid_filepath(save_folder):   
>         try: os.makedirs(save_folder)        
>         except WindowsError():
>             print("Check directory creation!\n")
> ```
> 
> [路径验证](https://pathvalidate.readthedocs.io/en/latest/index.html)库是必需的。
